version: '3.8'

services:
  jenkins:
    build:
      context: .
    container_name: my_jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - type: bind
        source: ./jenkins_home
        target: /var/jenkins_home
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/local/bin/docker'
      - './ssh:/var/jenkins_home/.ssh'